name: Publish Release
on:
  release:
    types:
      - created

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: 16
          distribution: 'adopt'
      - name: Cache Gradle packages
        uses: actions/cache@v2.1.6
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Build Rosie
        run: ./gradlew --stacktrace jar shadowJar
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: build/libs/Telegram-Orga-Bot-Rosie-*.jar

  upload-artifact:
    name: Upload artefact
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: artifact
          path: build/libs/
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/libs/Telegram-Orga-Bot-Rosie-*.jar
